### ISSUE TITLE
Plugin should not throw exception when an object property is selected

### ISSUE THREAD

**Issue by rsgoncalves** [co-ode-owl-plugins/owldoc#1]
Protege 5 beta-19 and OWLDoc v3.0.0. 

Selecting an object property from the object property hierarchy results in the exception below. 

``` java
org.semanticweb.owlapi.model.OWLRuntimeException: Not a data property!
    at uk.ac.manchester.cs.owl.owlapi.OWLObjectPropertyImpl.asOWLDataProperty(OWLObjectPropertyImpl.java:175)
    at org.coode.html.doclet.DomainsDoclet.getAssertedElements(DomainsDoclet.java:32)
    at org.coode.html.doclet.AbstractOWLElementsDoclet.getElements(AbstractOWLElementsDoclet.java:67)
    at org.coode.html.doclet.ElementsDoclet.renderHeader(ElementsDoclet.java:57)
    at org.coode.html.doclet.AbstractHTMLDoclet.renderAll(AbstractHTMLDoclet.java:50)
    at org.coode.html.doclet.AbstractHTMLDoclet.renderContent(AbstractHTMLDoclet.java:43)
    at org.coode.html.doclet.AbstractHTMLDoclet.renderAll(AbstractHTMLDoclet.java:51)
    at org.coode.browser.protege.OWLDocView$2.run(OWLDocView.java:151)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ignazio1977** [comment]
Another bug in owlhtml. Bad assumption on type of user object.

**Comment by ignazio1977** [comment]
Next release of ontology-browser will fix this

**Comment by johardi** [comment]
The ontology-browser-4.3.0 is now released
