### ISSUE TITLE
NullPointerException after running a reasoner

### ISSUE THREAD

**Issue by johardi** [co-ode-owl-plugins/owldoc#2]
Steps to reproduce the error:
1. Open an ontology,
2. Run a reasoner,
3. Open OWLDoc view and select any class entity.

```
java.lang.NullPointerException
    at org.coode.owl.util.OWLUtils.isStructural(OWLUtils.java:202)
    at org.coode.html.doclet.SuperclassesDoclet.getInferredElements(SuperclassesDoclet.java:57)
    at org.coode.html.doclet.AbstractOWLElementsDoclet.getElements(AbstractOWLElementsDoclet.java:69)
    at org.coode.html.doclet.ElementsDoclet.renderHeader(ElementsDoclet.java:57)
    at org.coode.html.doclet.AbstractHTMLDoclet.renderAll(AbstractHTMLDoclet.java:50)
    at org.coode.html.doclet.AbstractHTMLDoclet.renderContent(AbstractHTMLDoclet.java:43)
    at org.coode.html.doclet.AbstractHTMLDoclet.renderAll(AbstractHTMLDoclet.java:51)
    at org.coode.browser.protege.OWLDocView$2.run(OWLDocView.java:151)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ignazio1977** [comment]
Bug in owlmanager and in the reasoner used: the reasoner is guaranteed not null at that point, but there is no guarantee that the reasoner name is not null. However the reasoner should be nice about it.

Can be fixed in OWLUtils.

**Comment by ignazio1977** [comment]
See https://github.com/co-ode-owl-plugins/ontology-browser/commit/4128a65136d781100a8f9a161ac42421aef6ed4c

**Comment by ignazio1977** [comment]
Will be fixed with the next release of ontology-browser

**Comment by johardi** [comment]
The [ontology-browser-4.3.0](https://github.com/co-ode-owl-plugins/ontology-browser/releases/tag/ontology-browser-4.3.0) is now released
