### ISSUE TITLE
If export directory does not exist, OWLDoc shows an empty error dialog

### ISSUE THREAD

**Issue by tudorache** [co-ode-owl-plugins/owldoc#4]
OWLDoc should create the export directory if it does not exist. 

Currently, it will show an empty error dialog:
![screenshot - 02222016 - 02 33 39 pm](https://cloud.githubusercontent.com/assets/2709502/13235235/be66333e-d971-11e5-86a7-973f8bc8d3f7.png)

Exception in the console:

```
CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot
******************************************************************************** 
**                                  Protege                                   ** 
******************************************************************************** 

----------------- Initialising and Starting the OSGi Framework ----------------- 
FrameworkFactory Class: org.apache.felix.framework.FrameworkFactory 

The OSGi framework has been initialised 
------------------------------- Starting Bundles ------------------------------- 
Starting bundle org.protege.common 
Starting bundle org.eclipse.equinox.supplement 
Starting bundle org.eclipse.equinox.common 
Starting bundle org.protege.editor.core.application 
Starting bundle org.eclipse.equinox.registry 
Starting bundle org.protege.editor.core.application 
Starting bundle org.eclipse.equinox.registry 
Starting bundle org.apache.commons.io 
Starting bundle org.eclipse.equinox.supplement 
Starting bundle org.protege.editor.owl 
Starting bundle slf4j.api 
Starting bundle com.google.guava 
Starting bundle org.eclipse.equinox.common 
Starting bundle jul.to.slf4j 
Starting bundle ch.qos.logback.classic 
Starting bundle org.apache.servicemix.bundles.javax-inject 
Starting bundle org.semanticweb.owl.owlapi 
Starting bundle ch.qos.logback.core 
Not starting bundle com.google.inject.assistedinject explicitly because it is a fragment bundle. 
Starting bundle log4j.over.slf4j 
Not starting bundle com.google.inject.multibindings explicitly because it is a fragment bundle. 
Starting bundle org.protege.common 
Starting bundle com.google.inject 
Starting bundle org.apache.servicemix.bundles.aopalliance 
Starting bundle org.semanticweb.hermit 
Starting bundle code-generation 
Starting bundle org.coode.owlviz 
Starting bundle org.protege.owl.rdf 
Starting bundle cellfie 
Starting bundle existentialquery 
Starting bundle org.protege.editor.owl.rdf 
Starting bundle org.protege.ontograf 
Starting bundle uk.ac.manchester.cs.owl.explanation 
Starting bundle org.coode.dlquery 
Starting bundle swrltab-plugin 
Starting bundle org.coode.browser 
The OSGi framework has been started 

------------------------------------ Protégé ----------------------------------- 
Protégé Desktop 
Version 5.0.0, Build beta-23 


----------------------------------- Platform ----------------------------------- 
Java: JVM 1.8.0_40-b26  Memory: 466M 
Language: en, Country: US 
Framework: Apache Software Foundation (1.7)  
OS: linux (3.13.0-77-generic) 
Processor: x86-64


------------------------------------ Plugins ----------------------------------- 
Plugin: HermiT (1.3.8.413) 
Plugin: OWL Code Generation Plug-in (2.0.0) 
Plugin: OWLViz (5.0.1) 
Plugin: OWLAPI RDF Library (2.0.1) 
Plugin: Cellfie Protege 5.0+ Plugin (2.0.0.beta-6) 
Plugin: Existential Query (2.0.0) 
Plugin: Protege SPARQL Plugin (2.0.1) 
Plugin: OntoGraf (2.0.2) 
Plugin: Explanation Workbench (3.0.0) 
Plugin: DL Query (3.0.1) 
Plugin: SWRLTab Protege 5.0+ Plugin (1.0.0.beta-10) 
Plugin: OWLDoc (3.0.2) 

    OWLAPI RDF Library Plugin has no plugin.xml resource 
OWL API Version: 4.1.3.20151118-2017 
Cannot generate ontology catalog for ontology at http://www.semanticweb.org/ttania/ontologies/2016/1/untitled-ontology-160 
------------------------------- Auto-update Check ------------------------------ 
Auto-update last performed: Mon Feb 22 12:23:33 PST 2016 
Auto-update has been performed today.  Not performing it again. 

### Excluding compile: javax.swing.text.GlyphView::getBreakSpot
OWL API Version: 4.1.3.20151118-2017 
------------------------------- Loading Ontology ------------------------------- 
Loading ontology from http://protege.stanford.edu/ontologies/pizza/pizza.owl 
Loading OntologyID(Anonymous-0) from http://protege.stanford.edu/ontologies/pizza/pizza.owl 
URL connection input stream is compressed using gzip 
dumping remaining triples 
_:genid419 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
_:genid413 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
_:genid395 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
_:genid407 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
_:genid401 -> http://www.w3.org/1999/02/22-rdf-syntax-ns#type -> http://www.w3.org/2002/07/owl#AllDifferent 
done dumping remaining triples 
Loading for ontology and imports closure successfully completed in 645 ms 

---------------------------- Disposing of Workspace ---------------------------- 
Saved tab state for 'Individuals by class' tab 
Saved tab state for 'DL Query' tab 
Saved tab state for 'Active Ontology' tab 
Saved tab state for 'Entities' tab 
Saved workspace 
Disposed of 'Individuals by class' tab 
Disposed of 'DL Query' tab 
Disposed of 'Active Ontology' tab 
Disposed of 'Entities' tab 
Disposed of workspace 

An error was thrown: Root is not a directory: /home/ttania/Desktop/owldoc 
java.lang.Exception: Root is not a directory: /home/ttania/Desktop/owldoc
    at org.coode.html.OntologyExporter.export(OntologyExporter.java:181) ~[na:na]
    at org.coode.browser.protege.ExportOWLDocAction$1.run(ExportOWLDocAction.java:80) ~[na:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]

```

**Comment by ignazio1977** [comment]
Commit https://github.com/co-ode-owl-plugins/ontology-browser/commit/7128642338203df67eb68547fef415251602a95b should improve the situation.
If the folder does not exist, it will attempt to create it. If creation fails, an error will be thrown. If there is a file with the same name as the folder to create, a (different) error will be thrown as well.

**Comment by ignazio1977** [comment]
As for the others, new release of ontology-browser required :-)

**Comment by johardi** [comment]
The [ontology-browser-4.3.0](https://github.com/co-ode-owl-plugins/ontology-browser/releases/tag/ontology-browser-4.3.0) is now released
