### ISSUE TITLE
Some ontology IRIs can cause OWLDoc to crash with an IOException

### ISSUE THREAD

**Issue by matthewhorridge** [co-ode-owl-plugins/owldoc#7]
I have a problem if the Ontology URI has a second colon, e.g.
<conti:acd:model>

The OWL wizard stops with the following exception. I think it is because the
exporter tries to create files containing a ':' which is forbidden. Is this
issue already known?

```java
java.io.IOException: The filename, directory name, or volume label syntax is
incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.coode.html.OntologyExporter.ensureExists(OntologyExporter.java:353)
	at
org.coode.html.OntologyExporter.exportReferencedEntities(OntologyExporter.java:292)
	at
org.coode.html.OntologyExporter.exportReferencedEntities(OntologyExporter.java:241)
	at
org.coode.html.OntologyExporter.exportOntology(OntologyExporter.java:225)
	at org.coode.html.OntologyExporter.export(OntologyExporter.java:179)
	at
org.coode.browser.protege.ExportOWLDocAction$1.run(ExportOWLDocAction.java:80)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yasenstar** [comment]
I have this same problem in Windows 11

```
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.coode.html.OntologyExporter.ensureExists(OntologyExporter.java:353)
	at org.coode.html.OntologyExporter.exportReferencedEntities(OntologyExporter.java:292)
	at org.coode.html.OntologyExporter.exportReferencedEntities(OntologyExporter.java:241)
	at org.coode.html.OntologyExporter.exportOntology(OntologyExporter.java:225)
	at org.coode.html.OntologyExporter.export(OntologyExporter.java:179)
	at org.coode.browser.protege.ExportOWLDocAction$1.run(ExportOWLDocAction.java:80)
	at java.lang.Thread.run(Thread.java:745)
```
